version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    container_name: ovh-backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_SECRET_KEY=${API_SECRET_KEY}
        - VITE_FRONTEND_PASSWORD=${FRONTEND_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    container_name: ovh-frontend

